orbs:
  heroku: circleci/heroku@1.2.6
  jira: circleci/jira@1.3.1
version: 2.1
workflows:
  heroku_deploy:
    jobs:
      - build
      # - heroku/deploy-via-git:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only: main
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:16.3.0
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm@8"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install --legacy-peer-deps
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run Prettier test
          command: npm run check-format
      # - run:
      #     name: Run Prisma db setup
      #     command: npx prisma db pull && npx prisma generate
      - run:
          name: Run build test
          command: npm run test-all

    # post-steps:
    #   - run: your-database-migration-command
    # pre-steps:
    #   - run: command-that-run-before-deploying